# Generated by Django 5.2.14 on 2026-05-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="approvalrequest",
            new_name="approvals_a_workspa_f13216_idx",
            old_name="approvals_a_workspa_d6d96e_idx",
        ),
    ]
