# Generated by Django 5.2.14 on 2026-05-08 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MCPProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("kali", "Kali MCP (streamable-http)"),
                            ("hexstrike", "HexStrike API"),
                        ],
                        max_length=16,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("enabled", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_ok", models.BooleanField(default=False)),
                ("last_health_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MCPTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tactic",
                    models.CharField(
                        choices=[
                            ("TA0001", "Initial Access"),
                            ("TA0002", "Execution"),
                            ("TA0003", "Persistence"),
                            ("TA0004", "Privilege Escalation"),
                            ("TA0005", "Defense Evasion"),
                            ("TA0006", "Credential Access"),
                            ("TA0007", "Discovery"),
                            ("TA0008", "Lateral Movement"),
                            ("TA0009", "Collection"),
                            ("TA0011", "Command & Control"),
                            ("TA0042", "Resource Development"),
                            ("TA0043", "Reconnaissance"),
                            ("util", "Utility"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("med", "Medium"),
                            ("high", "High"),
                            ("crit", "Critical"),
                        ],
                        default="low",
                        max_length=8,
                    ),
                ),
                (
                    "schema",
                    models.JSONField(default=dict, help_text="JSON schema of input arguments"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="mcp.mcpprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["tactic", "name"],
                "unique_together": {("provider", "name")},
            },
        ),
    ]
