# Generated by Django 5.2.14 on 2026-05-09 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_workspace_llm_fallback_chain"),
        ("mcp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptool",
            name="risk_source",
            field=models.CharField(
                choices=[
                    ("annotation", "Provider annotation"),
                    ("heuristic", "Name heuristic"),
                    ("manual", "Manual override"),
                ],
                default="heuristic",
                help_text="How the current ``risk_level`` was determined.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="mcptool",
            name="risk_level",
            field=models.CharField(
                choices=[("low", "Low"), ("med", "Medium"), ("high", "High"), ("crit", "Critical")],
                default="med",
                help_text="Default to 'med' so unknown tools require Lead/Owner approval. Lower the level only after a manual review.",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="MCPToolRiskOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("med", "Medium"),
                            ("high", "High"),
                            ("crit", "Critical"),
                        ],
                        max_length=8,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_risk_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_overrides",
                        to="mcp.mcptool",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_risk_overrides",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("workspace", "tool")},
            },
        ),
    ]
