# Generated by Django 5.2.14 on 2026-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0002_mcptool_risk_source_alter_mcptool_risk_level_and_more"),
        ("mitre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcptool",
            name="techniques",
            field=models.ManyToManyField(
                blank=True,
                help_text="MITRE techniques this tool maps to. Curated via ``apps/mitre/data/tool_technique_map.json`` and applied with ``python manage.py sync_tool_technique_map``.",
                related_name="tools",
                to="mitre.mitretechnique",
            ),
        ),
    ]
