# Generated by Django 5.2.14 on 2026-05-10 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_workspace_llm_fallback_chain"),
    ]

    operations = [
        migrations.CreateModel(
            name="MitreTactic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tactic_id", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("short_name", models.SlugField(max_length=40)),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveSmallIntegerField()),
                ("references", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MitreTechnique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("technique_id", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.SlugField(max_length=80)),
                ("description", models.TextField(blank=True, default="")),
                ("is_subtechnique", models.BooleanField(default=False)),
                ("is_custom", models.BooleanField(default=False)),
                ("references", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_techniques",
                        to="mitre.mitretechnique",
                    ),
                ),
                (
                    "tactic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="techniques",
                        to="mitre.mitretactic",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set ONLY when is_custom=True. Built-in techniques are workspace-agnostic.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_techniques",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["tactic__order", "technique_id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_custom", True), ("workspace__isnull", False)),
                            models.Q(("is_custom", False), ("workspace__isnull", True)),
                            _connector="OR",
                        ),
                        name="mitre_custom_iff_workspace",
                    )
                ],
            },
        ),
    ]
