# Generated by Django 5.2.14 on 2026-05-08 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("domain", "Domain"),
                            ("ip", "IP address"),
                            ("cidr", "CIDR range"),
                            ("url", "URL"),
                        ],
                        default="domain",
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(help_text="Domain / IP / CIDR / URL", max_length=500)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("workspace", "value")},
            },
        ),
        migrations.CreateModel(
            name="ScopeRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Regex / CIDR / glob pattern to match", max_length=500
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        default="allow",
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_rules",
                        to="targets.target",
                    ),
                ),
            ],
            options={
                "ordering": ["target", "action", "pattern"],
            },
        ),
    ]
