# Generated by Django 5.2.14 on 2026-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="llm_fallback_chain",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of provider kinds the LLM router falls back to when the requested provider is unhealthy. The default is filled in by ``apps.llm.router`` from ``LLM_DEFAULT_FALLBACK_CHAIN`` settings.",
            ),
        ),
    ]
