# Generated by Django 5.2.14 on 2026-05-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="llmtrace",
            new_name="llm_llmtrac_session_60e96a_idx",
            old_name="llm_llmtrac_session_4a1c2c_idx",
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="model_name",
            field=models.CharField(default="", max_length=120),
        ),
    ]
