# Generated by Django 5.2.14 on 2026-05-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "llm",
            "0002_rename_llm_llmtrac_session_4a1c2c_idx_llm_llmtrac_session_60e96a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="llmtrace",
            name="fallback_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reason the router downgraded or fell back from the requested provider. Empty when the requested provider was used as-is.",
                max_length=240,
            ),
        ),
    ]
