# Generated by Django 5.2.14 on 2026-05-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_llmtrace_fallback_reason"),
        ("playbooks", "0001_initial"),
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="anchored_playbook",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, the chat is anchored to this playbook's technique + tool list.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anchored_chat_sessions",
                to="playbooks.playbook",
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="anchored_target",
            field=models.ForeignKey(
                blank=True,
                help_text="Target referenced by the system prompt when ``anchored_playbook`` is set.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anchored_chat_sessions",
                to="targets.target",
            ),
        ),
    ]
