# Generated by Django 5.2.14 on 2026-05-10 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_workspace_llm_fallback_chain"),
        ("engagements", "0001_initial"),
        ("mcp", "0003_mcptool_techniques"),
        ("mitre", "0001_initial"),
        ("targets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("manual", "Manual single-tool"),
                            ("recon", "Reconnaissance"),
                            ("web-audit", "Web Audit"),
                            ("ad-audit", "AD Audit"),
                            ("comprehensive", "Full Pentest"),
                        ],
                        default="recon",
                        max_length=24,
                    ),
                ),
                ("is_built_in", models.BooleanField(default=False)),
                (
                    "risk_envelope",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("med", "Medium"),
                            ("high", "High"),
                            ("crit", "Critical"),
                        ],
                        default="med",
                        help_text="Highest risk level the playbook may execute without explicit force.",
                        max_length=8,
                    ),
                ),
                (
                    "on_step_failure",
                    models.CharField(
                        choices=[
                            ("stop", "Stop run"),
                            ("skip", "Skip step + continue"),
                            ("ask", "Ask the operator"),
                        ],
                        default="stop",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbooks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playbooks",
                        to="mitre.mitretechnique",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="null = built-in, shared across workspaces.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbooks",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("workspace", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PlaybookRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("awaiting", "Awaiting approval"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "arg_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-step user overrides keyed by step.order, e.g. {'1': {'url': '...'}}",
                    ),
                ),
                (
                    "on_step_failure_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stop", "Stop run"),
                            ("skip", "Skip step + continue"),
                            ("ask", "Ask the operator"),
                        ],
                        default="",
                        help_text="If set, overrides the playbook's on_step_failure for this run.",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_run",
                        to="engagements.engagement",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="playbooks.playbook",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playbook_runs_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playbook_runs",
                        to="targets.target",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbook_runs",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybookStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "arg_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Jinja2-style placeholders, e.g. {'url': '{{ target.value }}'}. Vars: target.{value,kind,name}, workspace.{slug,name}, step.<N>.{stdout,structured,rendered_args}.",
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                ("timeout_sec", models.PositiveIntegerField(default=600)),
                (
                    "playbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="playbooks.playbook",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="playbook_steps",
                        to="mcp.mcptool",
                    ),
                ),
            ],
            options={
                "ordering": ["playbook", "order"],
                "unique_together": {("playbook", "order")},
            },
        ),
        migrations.CreateModel(
            name="PlaybookRunStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("awaiting", "Awaiting approval"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("rendered_args", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbook_run_step",
                        to="engagements.toolexecution",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="playbooks.playbookrun",
                    ),
                ),
                (
                    "template_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_steps",
                        to="playbooks.playbookstep",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "order"],
                "unique_together": {("run", "order")},
            },
        ),
    ]
